cs_code/code_test/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    # path('products/', TemplateView.as_view(template_name='product_list.html'), name='product_list'),
    path('products/', views.products, name='products_list'),
    path('product/<int:product_id>', views.product, name='product_detail'),
    path('product/<int:product_id>/edit', views.productedit, name='product_edit'),
    path('createproduct/', views.createproduct, name='product_create'),
    path('inventory/', views.inventory, name='inventory'),
]

cs_code/cs_code/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('code_test.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

cs_code/code_test/models.py
from django.db import models
from django.db.models.deletion import PROTECT
from django.db.models.fields import SmallIntegerField

from django.contrib.auth.models import User

from django.forms import ModelForm, widgets, HiddenInput

class BillingPlan(models.Model):
    billing_plan_name = models.CharField(max_length=255)

    def __str__(self):
        return self.billing_plan_name

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    password_plain = models.CharField(max_length=255)
    shop_name = models.CharField(max_length=255)
    remember_token = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(editable=False, 
                                      auto_now_add=True, 
                                      auto_now=False)
    updated_at = models.DateTimeField(auto_now=True,
                                      blank=True, 
                                      null=True)
    card_brand = models.CharField(max_length=255)
    card_last_four = models.CharField(max_length=4)
    trial_ends_at = models.DateTimeField()
    shop_domain = models.CharField(max_length=255)
    is_enabled = models.BooleanField(default=True)
    billing_plan = models.ForeignKey(BillingPlan, on_delete=PROTECT)
    trial_starts_at = models.DateTimeField()




    def __str__(self):
        return f'{self.name} of {self.shop_name}'

class Brand(models.Model):
    brand_name = models.CharField(max_length=255)

    def __str__(self):
        return self.brand_name


class Style(models.Model):
    style_name = models.CharField(max_length=255)

    def __str__(self):
        return self.style_name


class ProductType(models.Model):
    product_type_name = models.CharField(max_length=255)

    def __str__(self):
        return self.product_type_name


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    description = models.TextField()
    style = models.ForeignKey(Style, 
                              on_delete=models.PROTECT)
    brand = models.ForeignKey(Brand, 
                              on_delete=models.PROTECT)
    created_at = models.DateTimeField(editable=False, 
                                      auto_now_add=True, 
                                      auto_now=False)
    updated_at = models.DateTimeField(auto_now=True,
                                      blank=True, 
                                      null=True)
    url = models.TextField(default='', blank=True)
    product_type = models.ForeignKey(ProductType, 
                                     on_delete=models.PROTECT)
    shipping_price = models.IntegerField()
    note = models.TextField(default='', blank=True)
    admin = models.ForeignKey(Admin, on_delete=PROTECT)

    def __str__(self):
        return f'{self.id} {self.product_name}'


class Inventory(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.PROTECT)
    quantity = models.IntegerField()
    color = models.CharField(max_length=255)
    size = models.CharField(max_length=255)
    weight = models.FloatField()
    price_cents = models.IntegerField()
    sale_price_cents = models.IntegerField()
    cost_cents = models.IntegerField()
    sku = models.CharField(max_length=255)
    length = models.FloatField()
    width = models.FloatField()
    height = models.FloatField()
    note = models.TextField()

    def __str__(self):
        return '{} {} {} {}'.format(self.product.product_name,
                                 self.color,
                                 self.size,
                                 self.quantity)

    class Meta:
        verbose_name_plural = "Inventories"


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=PROTECT)
    inventory = models.ForeignKey(Inventory, on_delete=PROTECT)
    street_address = models.TextField()
    apartment = models.TextField()
    city = models.TextField()
    state = models.TextField()
    country_code = models.CharField(max_length=255)
    zip = models.TextField()
    phone_number = models.CharField(max_length=255)
    email = models.TextField()
    name = models.CharField(max_length=255)
    order_status = models.CharField(max_length=255)
    payment_ref = models.TextField()
    transaction_id = models.CharField(max_length=255)
    payment_amt_cents = models.IntegerField()
    ship_charged_cents = models.IntegerField(null=True)
    ship_cost_cents = models.IntegerField(null=True)
    subtotal_cents = models.IntegerField()
    total_cents = models.IntegerField()
    shipper_name = models.TextField()
    payment_date = models.DateTimeField(blank=True, 
                                        null=True)
    shipped_date = models.DateTimeField(blank=True, 
                                        null=True)
    tracking_number = models.TextField()
    tax_total_cents = models.IntegerField()
    created_at = models.DateTimeField(editable=False, 
                                      auto_now_add=True, 
                                      auto_now=False)
    updated_at = models.DateTimeField(auto_now=True,
                                      blank=True, 
                                      null=True)

    def __str__(self):
        return '{} {} {} {} {}'.format(self.name,
                                    self.city,
                                    self.state,
                                    self.country_code,
                                    self.shipped_date)


class ProductForm(ModelForm):
    
    class Meta:
        model = Product
        fields = ['product_name',
                  'description',
                  'style',
                  'brand',
                  'url',
                  'product_type',
                  'shipping_price',
                  'note',
                  'admin',]
        widgets = {'admin': HiddenInput()}

cs_code/code_test/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import context, loader
from django.db.models import Sum, F


from .models import *

def index(request):
    # return render(request, 'code_test/index.html')
    return render(request, 'code_test/home.html')

@login_required
def products(request):
    admin = Admin.objects.get(user_id=request.user.id)
    product_list = Product.objects.filter(admin_id=admin.id).annotate(potential_revenue=Sum(
                    F('inventory__quantity') * 
                    F('inventory__price_cents'),   
                    output_field=models.IntegerField()
                ))
    print(product_list.query)
    template = loader.get_template('code_test/product_list.html')
    
    context = {
        'product_list': product_list,
        'admin': admin,
    }
    return HttpResponse(template.render(context, request))


@login_required
def product(request, product_id):
    product = Product.objects.get(id=product_id)
    template = loader.get_template('code_test/product_detail.html')
    context = {
        'product': product,
    }
    return HttpResponse(template.render(context, request))


@login_required
def productedit(request, product_id):
    product = Product.objects.get(id=product_id)
    template = loader.get_template('code_test/product_edit.html')
    form = ProductForm(instance=product)
    context = {
        'product': product,
        'form': form,
    }
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        form.save()
        if form.is_valid():
            product = Product.objects.get(id=product_id)
            context['product'] = product
            template = loader.get_template('code_test/product_detail.html')
            return redirect('product_detail', product_id)
        else:
            for field in form:
                print("Field Error:", field.name,  field.errors)
 
    return HttpResponse(template.render(context, request))


@login_required
def createproduct(request):
    admin = Admin.objects.get(user_id=request.user.id)
    template = loader.get_template('code_test/product_create.html')
    form = ProductForm(initial={'admin': admin.id})
    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.cleaned_data['admin_id'] = admin.id
            product = form.save()
            return redirect('product_detail', product.id)

    return HttpResponse(template.render(context, request))


@login_required
def inventory(request):
    admin = Admin.objects.get(user_id=request.user.id)
    product_id = request.GET.get('product_id', None)
    sku = request.GET.get('sku', None)
    max_qty = request.GET.get('max_qty', None)
    filter = request.GET.get('filter', None)
    reset = request.GET.get('reset', None)
    inventory = Inventory.objects.filter(product__admin=admin.id)
    
    if filter:
        if product_id:
            inventory = inventory.filter(product_id=product_id)
        if sku:
            inventory = inventory.filter(sku=sku)
        if max_qty:
            inventory = inventory.filter(quantity__lte=max_qty)
    else:
        product_id = ''
        sku = ''
        max_qty = ''
    inv_sum = inventory.aggregate(Sum('quantity'))
    template = loader.get_template('code_test/inventory.html')
    context = {
        'inventory': inventory,
        'inv_sum': inv_sum['quantity__sum'],
        'admin': admin,
    }
    if product_id:
        context['filter_product_id'] = product_id
    if sku:
        context['filter_sku'] = sku
    if max_qty:
        context['filter_max_qty'] = max_qty
    return HttpResponse(template.render(context, request))

cs_code/code_test/templates/code_test/base.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/code_test/style.css' %}">
  <meta charset="utf-8">
  <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

cs_code/code_test/templates/code_test/home.html
{% extends 'base.html' %}

{% block title %}Home Base{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <h1>Hello and welcome to Home Base!</h1>
  <p>You are logged in as {{ user.username }}!</p>

  <p><a href="{% url 'products_list' %}">Products</a></p>
  <p><a href="{% url 'inventory' %}">Inventory</a></p>
  <p class="log_out"><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

cs_code/code_test/templates/code_test/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Home Base</title>
    </head>
    <body>
        <h1>Hello, and welcome to Home Base!</h1>
        {% if user.is_authenticated %}
            <h2>You are longged in as: {{ user.username }}</h2>
            <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <h2>You are not logged in.</h2>
            <a href="{% url 'login' %}">Log In</a>
        {% endif %}
    </body>
</html>

cs_code/code_test/templates/code_test/inventory.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}

  You are viewing your inventory {{ user.username }}!
  <p><a href="{% url 'index' %}">Return Home</a></p>
  <p class="log_out"><a href="{% url 'logout' %}">Log Out</a></p>
  {% if inv_sum %}
    <p>There are {{ inv_sum }} items in your inventory that meet your current filter conditions.</p>
  {% endif %}
  

<h2>Inventory</h2>
<form action="" method="get">
<p><label class="prop_label">Product ID</label><input type="text" id="product_id" name="product_id" value="{{ filter_product_id }}"/></p>
<p><label class="prop_label">Sku</label><input type="text" id="sku" name="sku" value="{{ filter_sku }}"/></p>
<p><label class="prop_label">Qty Below</label><input type="number" id="max_qty" name="max_qty" value="{{ filter_max_qty }}"/></p>
<p><input type="submit" name="filter" value="Filter" /> &nbsp; <input type="submit" name="reset" value="Reset" /></p>
</form>
{% if inventory %}
<table class="nospacing">
<tr>
<th>Product Name</th>
<th>Sku</th>
<th>Quantity</th>
<th>Color</th>
<th>Size</th>
<th>Price</th>
<th>Cost</th>
</tr>

{% for item in inventory %}
    <tr>
    <td>{{ item.product.product_name }}</td>
    <td>{{ item.sku }}</td>
    <td>{{ item.quantity }}</td>
    <td>{{ item.color }}</td>
    <td>{{ item.size }}</td>
    <td>{{ item.price_cents }}</td>
    <td>{{ item.cost_cents }}</td>
    </tr>
{% endfor %}
</table>
{% else %}
    <p>No products available</p>
{% endif %}
{% endblock %}

cs_code/code_test/templates/code_test/product_create.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}

<div class="product_detail">
<form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button style='margin-top:10px;' type='submit' >Save</button>
    </form>

<p><a href="{% url 'products_list' %}">Cancel</a></p>

</div>

<p><a href="{% url 'products_list' %}">Return to Products</a></p>
{% endblock %}

cs_code/code_test/templates/code_test/product_detail.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
{% if product %}
You are viewing the detail for product: {{ product }}!

<p><a href="{% url 'product_edit' product.id %}">Edit this product</a></p>

<div class="product_detail">
<p><span class="prop_label">Name:</span> <span class="prop_value">{{ product.product_name}}</span></p>
<p><span class="prop_label">Description:</span> <span class="prop_value">{{ product.description}}</span></p>
<p><span class="prop_label">Style:</span> <span class="prop_value">{{ product.style}}</span></p>
<p><span class="prop_label">Brand:</span> <span class="prop_value">{{ product.brand}}</span></p>
<p><span class="prop_label">Shipping Price:</span> <span class="prop_value">{{ product.shipping_price}}</span></p>
<p><span class="prop_label">Note:</span> <span class="prop_value">{{ product.note}}</span></p>
</div>
{% else %}
No product selected!
{% endif %}
<p><a href="{% url 'products_list' %}">Return to Products</a></p>
{% endblock %}

cs_code/code_test/templates/code_test/product_edit.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}

You are viewing the detail for product: {{ product }}!
<div class="product_detail">
<form action="{% url 'product_edit' product.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button style='margin-top:10px;' type='submit' >Save</button>
    </form>

<p><a href="{% url 'product_detail' product.id %}">Cancel</a></p>

</div>

<p><a href="{% url 'products_list' %}">Return to Products</a></p>
{% endblock %}

cs_code/code_test/templates/code_test/product_list.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}

  You are viewing your products {{ user.username }}!
  <p><a href="{% url 'index' %}">Return Home</a></p>
  <p class="log_out"><a href="{% url 'logout' %}">Log Out</a></p>
  <p><a href="{% url 'product_create' %}">New Product</a></p>
{% if product_list %}
<h2>Products</h2>

<table class="nospacing"><tr><th colspan="2"></th><th>Name</th><th>Style</th><th>Brand</th><th>Inventory</th></tr>
{% for product in product_list %}
    
        <tr><td><a href="{% url 'product_detail'  product.id %}">detail</a></td>
        <td><a href="{% url 'product_edit' product.id %}">edit</a></td>
        <td>{{ product.product_name }} 
        {% if product.inventory_set.all %} 
        <br> Potential Revenue: {{ product.potential_revenue }}
        {% endif %}
        </td><td> {{ product.style }} </td><td> {{ product.brand }} </td>
        <td>
        {% if product.inventory_set.all %}
        <a href="{% url 'inventory'  %}?product_id={{product.id}}&filter=Filter">Open inventory</a>
        <table class="nospacing"><tr><th>Qty</th><th>Color</th><th>Size</th><th>Sku</th><th>Price</th></tr>
        {% for sku in product.inventory_set.all %}
        <tr><td class="sku_qty">{{ sku.quantity }}</td>
        <td class="sku_color">{{ sku.color }}</td>
        <td class="sku_size">{{ sku.size }}</td>
        <td class="sku_sku">{{ sku.sku }}</td>
        <td class="sku_sku">{{ sku.price_cents }}</td></tr>
        {% endfor %}
        </table>
        {% else %}
        &nbsp;
        {% endif %}
        </td></tr>
    
{% endfor %}
</table>
{% else %}
    <p>No products available</p>
{% endif %}
{% endblock %}